# Generated by Django 3.0.3 on 2020-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('full_name', models.CharField(max_length=60)),
                ('hk_id', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
    ]
