# Generated by Django 3.0.3 on 2020-02-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdb', '0003_auto_20200224_2244'),
    ]

    operations = [
        migrations.RenameField('Client', 'client_id', 'client_ref')
    ]
