# Generated by Django 3.0.3 on 2020-02-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdb', '0005_auto_20200225_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-client_ref',)},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='lastname',
        ),
    ]
