# Generated by Django 3.0.3 on 2020-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdb', '0006_auto_20200225_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
