# Generated by Django 3.0.3 on 2020-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdb', '0010_auto_20200226_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
